ublox_gps_node:
  ros__parameters:
    debug: 1                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/tty_ACM0
    frame_id: gps
    uart1:
      baudrate: 460800
    gnss:
      glonass: true
      beidou: true
      gps: true
      qzss: true
      galileo: true
      imes: false
    # TMODE3 Config
    tmode3: 0                   # Survey-In Mode
    
    rtcm:
      in: true
      out: false

    rtcm_msgs:
      - 1005
      - 1077
      - 1087
      - 1097
      - 1127
      - 1230

    inf:
      all: true                   # Whether to display all INF messages in console
 
    publish:
      all: false
      nav:
        all: true
        relposned: true
        posllh: true
        posecef: true
        velned: true

    dgnss_mode: 3
