ublox_gps_node:
  ros__parameters:
    debug: 1

    device: /dev/ttyACM0
    frame_id: base
    dynamic_model: stationary
    fix_mode: auto
    dr_limit: 0

    gnss:
      gps: true
      glonass: true
      beidou: true
      galileo: true

    tmode3: 1
    sv_in:
      reset: true
      min_dur: 20
      acc_lim: 10.0

    rtcm:
      in: false
      out: true
      usb: true
      uart1:
        baudrate: 115200
        in: 0
        out: 3
      uart2:
        baudrate: 115200
        in: 0
        out: 3

    publish:
      all: true
      rxm:
        rtcm: true
      nav:
        relposned: true
        posllh: true
        posecef: true
        svin: true

    dgnss_mode: 3

