services:
  ros2-base-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: rtk-base-image
    container_name: ros2-base-container
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    stdin_open: true
    tty: true

