ublox_gps_node:
  ros__parameters:
    debug: 1                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/tty_Ardsimple
    frame_id: gps
    uart1:
      baudrate: 460800
    gnss:
      glonass: true
      beidou: true
      gps: true
      qzss: true
      galileo: true
      imes: false
    # TMODE3 Config
    tmode3: 1                   # Survey-In Mode
    
    survey_in:
      min_dur: 30
      acc_limit: 10

    rtcm:
      in: false
      out: true

    rtcm_msgs:
      - 1005
      - 1077
      - 1087
      - 1097
      - 1127
      - 1230
      - 4072_0
      - 4072_1

    inf:
      all: true                   # Whether to display all INF messages in console
 
    publish:
      all: false
      nav:
        all: true
        relposned: false
        posllh: true
        posecef: true

    dgnss_mode: 3
